### ISSUE TITLE
Can't save new tick

### ISSUE THREAD

**Issue by KoviRobi** [ucam-cl-dtg/urop-2014-ticking-ui#21]
Tried to create new tick (with testing system 2), did not work.

**Comment by as2388** [comment]
I can't reproduce this.

**Comment by isaac-dunn** [comment]
I can't reproduce this either.

**Comment by as2388** [comment]
Found the problem. If you have the audacity to not choose a correctness test the function which prepares the data to be submitted to the server fails.

**Comment by KoviRobi** [comment]
Also may have something to do vith `UROP-TestingSystem-dynamic2`, as that was the active one when we tried to create the tick, we reverted to `UROP-TestingSystem-dynamic` afterwards.

**Comment by as2388** [comment]
UROP-TestingSystem-dynamic2 has nothing to do with this front end Javascript bug
