### ISSUE TITLE
"rest" slot for tickers

### ISSUE THREAD

**Issue by KoviRobi** [ucam-cl-dtg/urop-2014-ticking-ui#30]
To mark as unbookable, if they want a break, etc.

**Comment by drt24** [comment]
The way we did this with last year's system was to have the tickers book themselves a slot. If they can't do this now if they have not submitted a tick then that might need fixing.

**Comment by isaac-dunn** [comment]
There is now a back end for tickers booking themselves slots without having submitted any ticks. All that is needed now is a front end button on each slot to call this endpoint. To unbook themselves from slots, tickers can use the "Remove {crsid} from slot" button - an error message will pop up, but it will work.
