### ISSUE TITLE
All ticks for all groups for you on dashboard

### ISSUE THREAD

**Issue by KoviRobi** [ucam-cl-dtg/urop-2014-ticking-ui#31]
Perhaps you could re-use some of the overview code?

**Comment by TomLefley** [comment]
I'll write a backend for this shortly

**Comment by as2388** [comment]
A better solution might be to add status icons to the tick tab in groups pages. This gives most of the functionality at much less effort. Then, to show everything on the dashboard, we can just load all those cards (but probably with restricted functionality so they can't open ticks) with templating
