### ISSUE TITLE
Tick names can't have apostrophes but error message only mentions spaces

### ISSUE THREAD

**Issue by drt24** [ucam-cl-dtg/urop-2014-ticking-ui#43]
Creating "Daniel's_test_tick" fails because it contains apostrophes but the error message is "Daniel's_test_tick". The best solution is probably to make this a proper display name and convert it to a canonical ID to use in urls.

**Comment by as2388** [comment]
So should we just the validation label or convert?

**Comment by drt24** [comment]
Just convert it. If you map spaces to underscores and map underscores to two underscores and strip out other invalid things like apostrophes (you want to use a whitelist of valid things to stop utf8 weirdness).

**Comment by TomLefley** [comment]
I feel like this should be handled on the front end, the backend should only ever be handed 'corrected' names

**Comment by drt24** [comment]
If you only want to store corrected names you need a mapping which turns the 'corrected name' back into the display name which is difficult so you probably need to at least store both.

**Comment by TomLefley** [comment]
I think I've got a fix for this, I'll work on it now

**Comment by TomLefley** [comment]
This is now all sorted, however creating "foo" and then foo will result in a clash however this is expected behaviour
