### ISSUE TITLE
Can't remove ticks from group page

### ISSUE THREAD

**Issue by as2388** [ucam-cl-dtg/urop-2014-ticking-ui#51]
I can add ticks one at a time, but can't remove any. Switching to checkboxes would solve this problem, and make it much quicker to add multiple ticks to group in quick succession

**Comment by TomLefley** [comment]
Are we going to do this then?

**Comment by as2388** [comment]
If we replace with checkboxes, we get this for free

**Comment by TomLefley** [comment]
Is this really something we can get done in the next hour?

**Comment by raahilshah** [comment]
We can do a simple delete button. Ticks aren't really going to be in the same number as members, so adding/deleting them one at a time should suffice, I guess.
