### ISSUE TITLE
Cannot scroll properly on touch devices

### ISSUE THREAD

**Issue by sacummins** [ucam-cl-dtg/urop-2014-ticking-ui#53]
On the Samsung tablet and other devices, users are unable to scroll if they happen to touch a card rather than an area around the card.

Either the area around the card needs to be big enough to select or the cards themselves should support scrolling.

**Comment by raahilshah** [comment]
X scrolling may interfere with swipeable cards. But no cards are swipeable right now. <br><br>:octocat: _Sent from [GH](http://nodegh.io)._
