### ISSUE TITLE
Report fails to open after its first submission

### ISSUE THREAD

**Issue by isaac-dunn** [ucam-cl-dtg/urop-2014-ticking-ui#55]
The first time a tick is submitted after being forked, the report fails to open once the tests complete. When it is resubmitted and the tests recomplete, the report opens as expected.

**Comment by as2388** [comment]
I cannot reproduce this. Please make sure you have the latest version, then list the exact steps you took which caused this. I thought I fixed this yesterday.

**Comment by isaac-dunn** [comment]
I just tried it on a new tick in a new group and it was fine. I assume something must have been outdated when I was trying this earlier.
