### ISSUE TITLE
Added tick not visible

### ISSUE THREAD

**Issue by drt24** [ucam-cl-dtg/urop-2014-ticking-ui#59]
I added a tick to 'Daniel's test group;' but it is not visible on the ticks tab, if I try to add it again I get an error saying it is already associated with the group.

**Comment by isaac-dunn** [comment]
This could be because the project was redeployed as you were doing this, and you need to revalidate with raven - try refreshing the page?

**Comment by as2388** [comment]
I can't see any ticks. This is because in order to fix another issue the back-end was modified and deployed before the front end was ready

**Comment by TomLefley** [comment]
My bad

**Comment by drt24** [comment]
Still not visible. Is it really fixed?

**Comment by TomLefley** [comment]
Try clearing your cache, they should be visible again
