### ISSUE TITLE
Ticking sessions are listed in order of creation date not their date

### ISSUE THREAD

**Issue by drt24** [ucam-cl-dtg/urop-2014-ticking-ui#63]
When there are a lot of sessions then having a consistent ordering is important and so they should be listed in order of when they are scheduled to occur rather than when they were created.

**Comment by isaac-dunn** [comment]
They're actually currently listed in alphabetical order.

**Comment by drt24** [comment]
Ahh that is what comes of naming things by random strings. Alphabetical order might be more sensible than occurrence date. Not sure.

**Comment by isaac-dunn** [comment]
The alphabetical order of their title, sorry, not their id. Either way, they are now sorted by their start date.
