### ISSUE TITLE
Dashboard loading overlay occasionally remains

### ISSUE THREAD

**Issue by isaac-dunn** [ucam-cl-dtg/urop-2014-ticking-ui#65]
Once the dashboard has finished loading (in firefox), the overlay from the loading icon sometimes remains (but is transparent), meaning that the page has to be refreshed for anything to respond.

**Comment by as2388** [comment]
And in Chrome

**Comment by raahilshah** [comment]
This is the same as Issue #1.

**Comment by TomLefley** [comment]
This almost always occurs when you move to another tab while the page is loading, ie the overlay is up

**Comment by TomLefley** [comment]
Do we have a fix for this yet or are we just writing it off as 'it happens every now and then?'
