### ISSUE TITLE
Book ticking slot button appears still for failed ticks after deadline

### ISSUE THREAD

**Issue by TomLefley** [ucam-cl-dtg/urop-2014-ticking-ui#72]
Though no ticking slots are available.

**Comment by as2388** [comment]
Isn't this intended? I thought the deadline was for submissions not ticking...

**Comment by as2388** [comment]
I don't think this is logical; however. It's just that this is how the existing system works. Which doesn't make it any better. Thoughts on this?

**Comment by as2388** [comment]
Will hide button and change front end logic to check if signed up first
